Add disk space monitoring
Varying-Vagrant-Vagrants/dashboard pull request #38
Opened 2021-03-15 06:39 UTC by evertiro

Fixes issue #2380

![Screen Shot 2021-03-15 at 2 17 06 AM](https://user-images.githubusercontent.com/36433/111113099-9b4ad400-8537-11eb-9de7-289db827d05e.png)

![Screen Shot 2021-03-15 at 2 37 39 AM](https://user-images.githubusercontent.com/36433/111113100-9be36a80-8537-11eb-8efa-fe550c6c401a.png)

2021-03-15 09:55 UTC, tomjn requested changes
Looks great, there's some tweaking to do and in the future I'd like to separate out some of the styling to be more generic ( this isn't the only thing that I want to use a progress bar indicator for )

2021-03-15 09:55 UTC, tomjn commented on dashboard-default.php
> +				require_once __DIR__ . '/php/blocks/sidebar/disk-info.php';
I'd move this further down the sidebar

2021-03-15 09:55 UTC, tomjn commented on php/blocks/sidebar/disk-info.php
> +	<h3>Disk Info</h3>
```suggestion
	<h3>Disk space</h3>
```

2021-03-15 09:55 UTC, tomjn commented on php/blocks/sidebar/disk-info.php
> +			<div class="disk-label">Virtual Machine</div>
```suggestion
			<div class="disk-label">VVV Guest Virtual Machine</div>
```

Lets eliminate as much ambiguity as possible

2021-03-15 09:55 UTC, tomjn commented on php/blocks/sidebar/disk-info.php
> +			<div class="disk-label">Physical Machine</div>
```suggestion
			<div class="disk-label">Host Machine</div>
```

2021-03-15 10:36 UTC, Mte90 commented
My only question is how much is performant this integration for the rest seems good.

2021-03-15 15:17 UTC, evertiro commented on dashboard-default.php
> +				require_once __DIR__ . '/php/blocks/sidebar/disk-info.php';
I put it at the top to mimic Plesk's positioning and so the visible indication would be obvious, but obviously it's movable wherever you'd like.

2021-03-15 15:20 UTC, evertiro commented
> My only question is how much is performant this integration for the rest seems good.

It's not dynamic, only checking on page load. In my tests the difference it makes in load time is negligible.

2021-03-16 16:26 UTC, evertiro commented
@tomjn I believe that covers all changes and brings it up to date

2021-03-16 17:31 UTC, tomjn approved these changes

2021-03-16 17:31 UTC, merged